### PR TITLE
Stickied discussions not showing when tag is hidden

### LINKED ISSUE #1833: Sticky posts are shown in all discussions when the tag is hidden from all discussions
## Bug Report

**Current Behavior**
Sticky post within a tag that is set to `Hide from All Discussions` is still shown on top of `All Discussions`.

**Steps to Reproduce**
1. Create a tag from the admin with `Hide from All Discussions` set.
2. Create a sticky post with that tag
3. Open all discussions

**Expected Behavior**
Sticky posts for a tag thats hidden from All Discussions should only be shown in that tag.

**Environment**
- Flarum version: 0.1.0-beta.9
- Website URL: https://community.carspending.com/

### PR DESCRIPTION
**Pull request by relax4o**
**Fixes [flarum/core#1833](https://github.com/flarum/core/issues/1833)**

Remove an unnecessary union query which is causing problems with the discussion listing on `All Discussions` page with `Latest` filter, by showing stickied topics even though it is attached to a hidden tag.

### CODE REVIEW

**Comment by dsevillamartin** [comment]
@relax4o Won't this change stop stickies from showing on the top of All Discussions if they are unread ?

**Comment by relax4o** [comment]
Not at all. Here's what was going on:

1. Takes all discussions (unstickied + stickied) ordered by `something`
2. Takes all stickied discussions ordered by `something` (same condition as 1st query)
3. Unites them
4. Adds another `order by` for the final results

What I did is:
1. Takes all discussions (unstickied + stickied)
2. Adds the final `order by` clause to the final result

The query does the same. I don't know if there was any specific reason of using `union`. It has a comment about making it more performant but I don't think how `union` would make it more performant than the simplification I've added.

I'll upload 2 screens in a minute.

**Comment by relax4o** [comment]
https://imgur.com/XiCzjvT
https://imgur.com/9tFtdhp

By the way, how to add screenshots so they can be visible directly in the post?

**Comment by relax4o** [comment]
@datitisev I've read again your question and just to be clear I need to ask this:

When a stickied topic is added to a hidden tag, should it appear in All Discussion no matter of the tag restriction?
Or when in hidden tag, should it appear in All Discussions only if it's unread?

**Comment by luceos** [comment]
> By the way, how to add screenshots so they can be visible directly in the post?

Copy paste them into the textarea. Or use markdown `title`.

Related to the actual PR, even though I am unsure we would want this behavior to exist, your code should use the Eloquent Query Builder not use raw statements and bindings. Because for one, if I'm not mistaken, you raw statements don't take database prefixes into consideration anymore.

**Comment by relax4o** [comment]
@luceos I haven't added any code. I just removed a piece and kept whatever was there.

Do you want me to revamp the query?

**Comment by luceos** [comment]
🙈 OH wow, sorry for this extremely rude oversight on my behalf. Leave it as is.

**Comment by relax4o** [comment]
Haha, it's okay. Leaving as is.

**Review by askvortsov1 — CHANGES_REQUESTED** [review]
After testing locally, it seems that unread, stickied discussions are indeed no longer pushed to the top. However, when looking at the origin/master branch, I'm not sure that this is still an issue: sticky posts in hidden discussions are not showing up on 'All Discussions' for me.

**Comment by askvortsov1** [comment]
Thanks again for the PR! I'm going to close this for now as it seems that the underlying https://github.com/flarum/core/issues/1833 is no longer an issue.

**Comment by askvortsov1** [comment]
Closing due to inactivity

**Pull request closed without merging**
