### PR TITLE
Fix evaluation of post content by m.trust()

### PR DESCRIPTION
**Pull request by SychO9**

### CODE REVIEW

**Review by askvortsov1 — APPROVED** [review]

**Review by clarkwinkelmann — COMMENTED** [review]
Looking good and tested locally.

Should we add a comment maybe? Like

    // Wrapping in <div> because ItemList entries need to be vnodes

Something else I thought of is that we can also use a text vnode. Unfortunately Mithril has no helper method to generate them, so that instantly makes the code less readable https://mithril.js.org/vnodes.html#vnode-types

This is how it would work if we wanted to use a text vnode. I tested it locally:

    items.add('excerpt', {tag: "#", children: excerpt}, -100);

EDIT: also probably not an issue, but was this branched out of an older version? The fix from 55cc45ccd36abf9078d0748fdfc4b2fbddb76cae isn't present when I checkout this PR. Should fix itself by merging anyway.

**Comment by SychO9** [comment]
I don't have a strong opinion on using a text vnode or wrapping in `div` 🤷🏼‍♂️ as long as it works. I haven't made that change but we can do it if anyone wants to ofc.

> EDIT: also probably not an issue, but was this branched out of an older version? The fix from 55cc45c isn't present when I checkout this PR. Should fix itself by merging anyway.

Ah yes, I seem to have forgotten to update my local master branch. Won't be a problem for git though.

**Review by clarkwinkelmann — APPROVED** [review]
Tested locally again, all good for me :+1:

**Review by imorland — APPROVED** [review]
tested locally. confirmed to resolve the issue

**Comment by luceos** [comment]
@SychO9 please provide a reason for a PR when creating one, that makes writing changelogs a ton easier ;)

**Pull request merged**
